// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgYbUfQScrKtwgUgzxtrYfs77E8sXm4Qo',
    appId: '1:18385046807:web:19aaef450fc8b702f73b52',
    messagingSenderId: '18385046807',
    projectId: 'insta-tut-90905',
    authDomain: 'insta-tut-90905.firebaseapp.com',
    storageBucket: 'insta-tut-90905.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFwfnK225cwgd_nngsf1mcoeDa--zV4YY',
    appId: '1:18385046807:android:d2b1401e9a58da98f73b52',
    messagingSenderId: '18385046807',
    projectId: 'insta-tut-90905',
    storageBucket: 'insta-tut-90905.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Gd7qpgrkllFky0CX4Js_fGtoNctbQpM',
    appId: '1:18385046807:ios:a5b7644b195f6312f73b52',
    messagingSenderId: '18385046807',
    projectId: 'insta-tut-90905',
    storageBucket: 'insta-tut-90905.appspot.com',
    iosClientId: '18385046807-59779hcvccr7ac7f8fppijdg4g7lagge.apps.googleusercontent.com',
    iosBundleId: 'com.example.instacloneRanavat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Gd7qpgrkllFky0CX4Js_fGtoNctbQpM',
    appId: '1:18385046807:ios:a5b7644b195f6312f73b52',
    messagingSenderId: '18385046807',
    projectId: 'insta-tut-90905',
    storageBucket: 'insta-tut-90905.appspot.com',
    iosClientId: '18385046807-59779hcvccr7ac7f8fppijdg4g7lagge.apps.googleusercontent.com',
    iosBundleId: 'com.example.instacloneRanavat',
  );
}
